#!/bin/bash

action() {
    local delay=$1; shift
    local n=$1; shift

    while [ $((n--)) -gt 0 ] ; do
	echo -ne 'GET rfc2616.txt HTTP/1.1\r\n\r\n'
	sleep $delay
    done
}

action $1 $2 | nc salix 8080 | wc
