.ig
$Id: gresabladet.1,v 1.1 2010-07-18 09:46:23 grahn Exp $
$Name:  $
..
.ss 12 0
.de BP
.IP \\fB\\$*
..
.
.
.TH gresabladet 1 "JUL 2010" "Gresabladet" "User Manuals"
.
.
.SH "NAME"
gresabladet \- local Netnews (NNTP) server
.
.
.SH "SYNOPSIS"
.B gresabladet
.RB [ \-d ]
.RB [ \-a
.IR listen-address ]
.RB [ \-p
.IR port ]
.br
.B gresabladet
.B --version
.br
.B gresabladet
.B --help
.
.
.SH "DESCRIPTION"
.
.
.SH "OPTIONS"
.BP \-d
.
.BP --version
Print version information and exit.
.
.BP --help
Print the usage message and exit.
.
.
.SH "FILES"
\-
.
.
.SH "ENVIRONMENT"
\-
.
.
.SH "BUGS"
\-
.
.
.SH "AUTHOR"
J\(:orgen Grahn \[fo]grahn+src@snipabacken.se\[fc]
.
.
.SH "LICENSE"
The Modified BSD license (also known as the 3-clause BSD license).
.
.
.SH "SEE ALSO"
.BP RFC\~3977 10x
Network News Transfer Protocol (NNTP)
.BP RFC\~4643
NNTP Extension for Authentication
.BP RFC\~2980
Common NNTP Extensions
.BP RFC\~5536
Netnews Article Format
.BP RFC\~5537
Netnews Architecture and Protocols
